-- Run in Supabase SQL Editor

-- 1. Savings Goals
create table savings_goals (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) default auth.uid(),
  name        text not null,
  target      numeric not null,
  saved       numeric default 0,
  deadline    date,
  color       text default '#059669',
  emoji       text default '🎯',
  created_at  timestamptz default now()
);
alter table savings_goals enable row level security;
create policy "Users own goals" on savings_goals for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2. Bills & Subscriptions
create table bills (
  id            bigint generated by default as identity primary key,
  user_id       uuid references auth.users(id) default auth.uid(),
  name          text not null,
  amount        numeric not null,
  due_day       integer not null check (due_day between 1 and 31),
  category      text,
  is_subscription boolean default false,
  is_active     boolean default true,
  created_at    timestamptz default now()
);
alter table bills enable row level security;
create policy "Users own bills" on bills for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
