-- Run this in Supabase: SQL Editor -> New query -> paste -> Run
-- Safe migration — all changes are additive, no existing data is modified.

-- 1. Add linked_categories to savings_goals.
--    Stored as a Postgres text[] (array of category name strings).
--    Existing rows get an empty array by default — no data loss.
alter table savings_goals
  add column if not exists linked_categories text[] default '{}';

-- 2. Goal Allocation History table.
--    Every time the user chooses YES to "allocate this expense to a goal",
--    a record is saved here so the goal's progress can be fully audited.
create table if not exists goal_allocations (
  id           bigint generated by default as identity primary key,
  user_id      uuid references auth.users(id) default auth.uid(),
  goal_id      bigint references savings_goals(id) on delete cascade,
  amount       numeric not null,
  note         text,
  category     text,
  allocated_at date not null default current_date,
  created_at   timestamptz default now()
);

alter table goal_allocations enable row level security;

create policy "Users own goal allocations"
  on goal_allocations for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
