-- Run this in Supabase: SQL Editor -> New query -> paste -> Run

-- 1. Pay cycle HISTORY table.
--    The old `pay_cycle` table only ever held ONE row per user (every save
--    overwrote it), so there was no history to look back on. This new table
--    keeps a row for every cycle you've ever started — that's what powers
--    the "Current Cycle / Previous Cycle" dropdown on the History page.
create table pay_cycles (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users(id) default auth.uid(),
  start_date date not null,
  end_date   date not null,
  created_at timestamptz default now()
);

alter table pay_cycles enable row level security;

create policy "Users can view own pay cycles"
  on pay_cycles for select
  using (auth.uid() = user_id);

create policy "Users can insert own pay cycles"
  on pay_cycles for insert
  with check (auth.uid() = user_id);

-- 2. Carry your existing single pay cycle (if any) over as the first
--    history row, so nobody loses their currently-set cycle.
insert into pay_cycles (user_id, start_date, end_date, created_at)
select user_id, start_date, end_date, coalesce(updated_at, now())
from pay_cycle;

-- Note: the old `pay_cycle` table is intentionally left in place (not
-- dropped) in case you need to roll back. The app no longer reads from or
-- writes to it after this migration — everything moves to `pay_cycles`.
