-- Run this in Supabase: SQL Editor -> New query -> paste -> Run

-- 1. Mark transactions as recurring
alter table transactions
  add column is_recurring boolean default false;

-- 2. New table for monthly category budgets
create table budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default auth.uid(),
  category text not null,
  monthly_limit numeric not null,
  created_at timestamptz default now(),
  unique (user_id, category)
);

-- 3. Lock it down per-user, same pattern as transactions
alter table budgets enable row level security;

create policy "Users can view own budgets"
  on budgets for select
  using (auth.uid() = user_id);

create policy "Users can insert own budgets"
  on budgets for insert
  with check (auth.uid() = user_id);

create policy "Users can update own budgets"
  on budgets for update
  using (auth.uid() = user_id);

create policy "Users can delete own budgets"
  on budgets for delete
  using (auth.uid() = user_id);
