-- Run this in Supabase: SQL Editor -> New query -> paste -> Run

-- 1. Categories you manage yourself (no more fixed list)
create table categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default auth.uid(),
  name text not null,
  type text not null check (type in ('income', 'expense')),
  created_at timestamptz default now(),
  unique (user_id, type, name)
);

alter table categories enable row level security;

create policy "Users can view own categories"
  on categories for select
  using (auth.uid() = user_id);

create policy "Users can insert own categories"
  on categories for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own categories"
  on categories for delete
  using (auth.uid() = user_id);

-- 2. Pay cycle (custom date range instead of calendar month)
create table pay_cycle (
  user_id uuid primary key references auth.users(id) default auth.uid(),
  start_date date not null,
  end_date date not null,
  updated_at timestamptz default now()
);

alter table pay_cycle enable row level security;

create policy "Users can view own pay cycle"
  on pay_cycle for select
  using (auth.uid() = user_id);

create policy "Users can insert own pay cycle"
  on pay_cycle for insert
  with check (auth.uid() = user_id);

create policy "Users can update own pay cycle"
  on pay_cycle for update
  using (auth.uid() = user_id);
