-- Run this in Supabase: SQL Editor -> New query -> paste -> Run
-- Safe migration — additive only, no existing data modified.

-- 1. Onboarding completion status in user_profiles.
--    NULL = never shown (new user), FALSE = skipped/incomplete, TRUE = complete.
alter table user_profiles
  add column if not exists onboarding_complete boolean default null;

-- 2. Credit cards table.
create table if not exists credit_cards (
  id                  bigint generated by default as identity primary key,
  user_id             uuid references auth.users(id) default auth.uid(),
  bank_name           text not null,
  nickname            text not null,
  credit_limit        numeric not null default 0,
  outstanding_balance numeric not null default 0,
  statement_date      integer,        -- day of month (1-31)
  payment_due_date    integer,        -- day of month (1-31)
  color               text default '#6366f1',
  created_at          timestamptz default now()
);

alter table credit_cards enable row level security;

create policy "Users own credit cards"
  on credit_cards for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 3. Add payment_method and credit_card_id to transactions.
--    payment_method: 'cash' | 'bank' | 'credit_card'
--    credit_card_id: references credit_cards(id), null for cash/bank
alter table transactions
  add column if not exists payment_method text default 'cash',
  add column if not exists credit_card_id bigint references credit_cards(id) on delete set null;
