-- Run this in Supabase: SQL Editor -> New query -> paste -> Run
-- Safe — additive only, no existing data modified.

-- Credit card transaction audit log.
-- Stores the net effect each transaction had on a credit card's outstanding balance.
-- effect_type: 'purchase' = increased outstanding, 'repayment' = decreased outstanding.
-- This is what allows Edit and Delete to reverse the previous effect accurately,
-- even if the card or category has since changed.
create table if not exists credit_card_transactions (
  id             bigint generated by default as identity primary key,
  user_id        uuid references auth.users(id) default auth.uid(),
  transaction_id bigint references transactions(id) on delete cascade,
  credit_card_id bigint references credit_cards(id) on delete cascade,
  amount         numeric not null,
  effect_type    text not null check (effect_type in ('purchase', 'repayment')),
  created_at     timestamptz default now()
);

alter table credit_card_transactions enable row level security;

create policy "Users own cc transactions"
  on credit_card_transactions for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
